### ISSUE TITLE
Incorrect edge display in RVIZ when tracking cloth

### ISSUE THREAD

**Issue by dcolli23** [UM-ARM-Lab/cdcpd#47]
# Description

When displaying cloth tracking in RVIZ, the edge markers are constructed using the rope edge function. Instead, the markers should be constructed from the tracked configuration's edges like in 953cebf2f7becc02a19fd368b1d8fc45c67f6fa8. This was fixed in another branch but the changes were never pulled into the main branch.

This issue was brought to my attention by Chen Li of Tsinghua University.

To Do:
- [x] Determine if I should pull in the TrackingMap changes
    - [x] If I do, create a PR from 953cebf2f7becc02a19fd368b1d8fc45c67f6fa8
    - [x] Add other commits in tree to fix RVIZ visualization.
- ~~If not, pull only relevant RVIZ changes from the commit above~~
    - ~~Pull any tests that are necessary.~~
    - ~~Adapt edge visualization function to only work with one template on master~~

**Comment by dcolli23** [comment]
The pull request mentioned above should resolve this issue. I'll merge to master soon. If you can test verify that the code in the pull request works, then I'll merge it to master. Thanks!

**Comment by lichenTHU** [comment]
It works well and thanks a lot.
![2023-03-28 15-42-12 的屏幕截图](https://user-images.githubusercontent.com/73934461/228164469-a88d81fc-80fd-42eb-83b0-19190b134333.png)

**Comment by dcolli23** [comment]
Fantastic! I'm happy things are working for you now. I'm going to close this issue but I'll keep the pull request (#50) open until someone in the lab can review the change.
